Change implemented `tf_instance` version from `0.2.0` to `0.3.3`
cloudposse/terraform-aws-ec2-admin-server pull request #13
Opened 2017-09-12 14:34 UTC by drama17

## What
* Change implemented `tf_instance` version from `0.2.0` to `0.3.3`

## Why
* We need to use newest version of `tf_instance` module here as it contain `userdata` and some other required changes

2017-09-12 16:23 UTC, const-bon requested changes

2017-09-12 16:23 UTC, comeanother commented on main.tf
>  module "instance" {
Update module according to the latest [tf_instance](https://github.com/cloudposse/tf_instance/blob/master/README.md) features.

2017-09-13 16:04 UTC, osterman submitted a review, later dismissed

2017-09-13 21:12 UTC, osterman submitted a review, later dismissed

2017-09-13 21:23 UTC, const-bon approved these changes

2017-09-13 21:23 UTC, merged