Add tf_hostname to tf_admin module
cloudposse/terraform-aws-ec2-admin-server pull request #3
Opened 2017-08-21 17:12 UTC by drama17

## What
* use `tf_hostname` to define the `admin` host in the `prod.autopay.cc` domain

## Why
* Need valid hostname for admin host

2017-08-21 17:19 UTC, drama17 commented
![1503335892259](https://user-images.githubusercontent.com/10601658/29530747-fa32d012-86ad-11e7-8280-00bfae078f14.jpg)

2017-08-21 17:59 UTC, osterman commented on outputs.tf
> +output "domain_name" {
Just call it `hostname` or `fqhn`

2017-08-21 18:00 UTC, osterman requested changes
Looks good, just one tweak for output variable name.

2017-08-22 07:47 UTC, drama17 commented on outputs.tf
> +output "domain_name" {
Renamed

2017-08-22 15:32 UTC, drama17 commented
![1503415704873](https://user-images.githubusercontent.com/10601658/29573651-37904c9a-8768-11e7-8647-331985b1ecde.jpg)

2017-08-22 15:33 UTC, drama17 commented
![1503415975597](https://user-images.githubusercontent.com/10601658/29573696-56e729ce-8768-11e7-894f-aa289e60a505.jpg)

2017-08-22 16:52 UTC, osterman requested changes
tf_domain does not belong here

2017-08-22 18:27 UTC, drama17 commented
![Uploading 1503426365032.jpg…]()
![1503426404374](https://user-images.githubusercontent.com/10601658/29581047-b10cde5e-8780-11e7-9c19-2cdd0d00626e.jpg)

2017-08-22 20:40 UTC, osterman approved these changes

2017-08-23 09:41 UTC, merged

2017-08-23 17:40 UTC, drama17 commented
![1503509843989](https://user-images.githubusercontent.com/10601658/29629926-3a61a9d8-8843-11e7-864c-8cbb3f1eb294.jpg)

2017-08-24 12:30 UTC, comeanother commented on main.tf
> +  ttl       = 60
Add `ttl` as variable.

2017-08-24 18:38 UTC, osterman commented on outputs.tf
> +output "fqdn" {
This is `fqhn` not `fqdn`