Update documentation
cloudposse/terraform-aws-ec2-admin-server pull request #5
Opened 2017-08-24 11:44 UTC by drama17

## What
* Update README.md

## Why
* Changes requested in https://app.asana.com/0/386406220258003/413152127654288

2017-08-24 12:19 UTC, const-bon requested changes

2017-08-24 12:19 UTC, comeanother commented on README.md
>  This will create a `id`, `fqdn`, `security_group_id`, `role` and `public_ip`.
`id`, `fqdn`, `security_group_id`, `role` and `public_ip` are outputs, but not created resources.
Delete it, as we have `tf_admin` purpose description at the top and outputs description at the bottom.

2017-08-24 12:19 UTC, comeanother commented on README.md
> +That is why `tf_domain` should be implemented in `root` module when we need `tf_admin`
That is why `tf_domain` should be implemented in `root` TF manifest when we need `tf_admin`

2017-08-24 12:19 UTC, comeanother commented on README.md
> +| `associate_public_ip_address`| `true`         | Define if the `public_ip` will be created for the instance                | No  |
Get description of `associate_public_ip_address` in `tf_instance`.

2017-08-24 12:19 UTC, comeanother commented on README.md
> +| `fqdn`              | Normalized name                                                   |
`fqdn` is not only `Normalized name`

2017-08-24 12:19 UTC, comeanother commented on README.md
> +| `public_ip`         | Normalized namespace                                              |
`public_ip` is not a `Normalized namespace`

2017-08-24 13:36 UTC, drama17 commented on README.md
>  This will create a `id`, `fqdn`, `security_group_id`, `role` and `public_ip`.
Done

2017-08-24 13:37 UTC, drama17 commented on README.md
> +That is why `tf_domain` should be implemented in `root` module when we need `tf_admin`
Not agree, need to discuss

2017-08-24 13:39 UTC, drama17 commented on README.md
> +| `associate_public_ip_address`| `true`         | Define if the `public_ip` will be created for the instance                | No  |
@comeanother please add more details what do you need me to change here

2017-08-24 13:41 UTC, drama17 commented on README.md
> +| `fqdn`              | Normalized name                                                   |
@comeanother So you mean I need to decrypt `fqdn` as 'Fully Qualified Domain Name'?

2017-08-24 13:43 UTC, drama17 commented on README.md
> +| `public_ip`         | Normalized namespace                                              |
Of course not. Fixed

2017-08-24 14:35 UTC, comeanother commented on README.md
> +| `fqdn`              | Normalized name                                                   |
Let's say `DNS name (Fully Qualified Domain Name) of creating instance`

2017-08-24 14:37 UTC, comeanother commented on README.md
> +| `associate_public_ip_address`| `true`         | Define if the `public_ip` will be created for the instance                | No  |
1. Navigate to [tf_instance](https://github.com/cloudposse/tf_instance/blob/master/README.md)
2. Copy description of `associate_public_ip_address` in  [tf_instance](https://github.com/cloudposse/tf_instance/blob/master/README.md)
3. Paste it into `tf_admin` `associate_public_ip_address` description.

2017-08-24 14:38 UTC, comeanother commented on README.md
> +That is why `tf_domain` should be implemented in `root` module when we need `tf_admin`
What are you against of?

2017-08-24 14:52 UTC, drama17 commented on README.md
> +| `fqdn`              | Normalized name                                                   |
Done

2017-08-24 15:00 UTC, drama17 commented on README.md
> +That is why `tf_domain` should be implemented in `root` module when we need `tf_admin`
Done

2017-08-24 15:00 UTC, drama17 commented on README.md
> +| `associate_public_ip_address`| `true`         | Define if the `public_ip` will be created for the instance                | No  |
Done

2017-08-24 17:32 UTC, osterman commented on README.md
> +That is why `tf_domain` should be implemented in `root` TF manifest when we need `tf_admin`
Missing ending `.`

2017-08-24 17:32 UTC, osterman commented on README.md
> +Module `tf_admin` requires another module to be used additionally - `tf_domain`
Missing ending `.`

2017-08-24 17:33 UTC, osterman commented on README.md
> +`tf_admin` uses `tf_hostname` to create a DNS record for created host. `tf_hostname` module needs `zone_id` parameter as an input, and this parameter actually is an output from `tf_domain`
missing ending `.`

2017-08-24 17:34 UTC, osterman commented on README.md
> +|:-------------------:|:-----------------------------------------------------------------:|
I prefer `:----` to `:----:`.  Use `:---:` for default values. Use `:----` for everything else.

2017-08-24 17:48 UTC, osterman commented on README.md
> +|:-------------------:|:-----------------------------------------------------------------:|
![image](https://user-images.githubusercontent.com/52489/29680540-b8fd82c8-88b9-11e7-9b96-8910c89c618a.png)

2017-09-01 17:45 UTC, osterman commented on README.md
> +|:-------------------:|:-----------------------------------------------------------------:|
This row is still wrong.

2017-09-05 18:48 UTC, osterman approved these changes

2017-09-06 17:35 UTC, const-bon approved these changes

2017-09-06 17:35 UTC, merged